pool:
  vmImage: ubuntu-latest

container:
  image: coverity-linux64-2020.12
  endpoint: acr-chuckaude

variables:
- group: coverity-azure
- name: COVERITY_TOOL_HOME
  value: /opt/coverity/analysis/2020.12
- name: COVERITY_PROJECT
  value: $(Build.Repository.Name)

steps:
- task: synopsys-coverity.synopsys-coverity-azure-devops.coverity-task.synopsys-coverity@1
  inputs:
    coverityService: 'coverity-azure'
    projectName: '$(COVERITY_PROJECT)'
    streamName: '$(COVERITY_PROJECT)-$(Build.SourceBranchName)'
    checkIssues: true
    issueView: 'Outstanding Issues'
    issueStatus: 'unstable'
    buildCommand: 'mvn -B package -DskipTests'
    customCommandArgs: true
    covBuildArgs: '--fs-capture-search $(Build.SourcesDirectory)'
    covAnalyzeArgs: '--ticker-mode none --strip-path $(Build.SourcesDirectory) --webapp-security'
    covCommitArgs: '--ticker-mode none --description $(Build.BuildURI) --version $(Build.SourceVersion) --scm git'
  displayName: 'Coverity Scan'
