pool:
  vmImage: ubuntu-latest

container:
  image: coverity-linux64-2020.12
  endpoint: acr-chuckaude

variables:
- group: coverity-azure
- name: COVERITY_TOOL_HOME
  value: /opt/coverity/analysis/2020.12
- name: COVERITY_PROJECT
  value: $(Build.Repository.Name)

steps:
- bash: |
    export PATH=$PATH:$COVERITY_TOOL_HOME/bin
    set -x
    cov-build --dir idir --fs-capture-search $(Build.SourcesDirectory) mvn -B package -DskipTests
    cov-analyze --dir idir --ticker-mode none --strip-path $(Build.SourcesDirectory) --webapp-security
    cov-commit-defects --dir idir --ticker-mode none --url $(COV_URL) --stream $(COVERITY_PROJECT)-$(Build.SourceBranchName) --description $(Build.BuildURI) --version $(Build.SourceVersion) --scm git
  env:
    COVERITY_PASSPHRASE: $(COVERITY_PASSPHRASE)
  displayName: 'Coverity Scan'
