pool:
  vmImage: ubuntu-latest

workspace:
  clean: all

variables:
  - name: PROJECT
    value: 'chuckaude-$(Build.Repository.Name)'

steps:
- task: synopsys-polaris.synopsys-polaris.synopsys-polaris-task.SynopsysPolaris@1
  inputs:
    polarisService: 'polaris-sipse'
    polarisCommand: '--co project.name=$(PROJECT) analyze -w -- mvn -B package -DskipTests'
  displayName: 'Polaris Scan'
