pool:
  vmImage: ubuntu-latest

workspace:
  clean: all

variables:
  - group: polaris-sipse
  - name: PROJECT
    value: 'chuckaude-$(Build.Repository.Name)'

steps:
- script: |
    curl -fLOsS $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
    unzip -d $(Agent.TempDirectory) -jo polaris_cli-linux64.zip
    $(Agent.TempDirectory)/polaris --co project.name=$(PROJECT) analyze -w -- mvn -B package -DskipTests
  env:
    POLARIS_ACCESS_TOKEN: $(POLARIS_ACCESS_TOKEN)
  displayName: 'Polaris Scan'
